dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: jenkinsx-demo2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: jenkinsx-demo3
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: jenkinsx-demo4
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
